{pkgs}: {
  deps = [
    pkgs.quicklispPackagesSBCL.fiveam
    pkgs.rPackages.gamlss_data
    pkgs.rPackages.Rvmmin
    pkgs.haskellPackages.gogol-playcustomapp
    pkgs.haskellPackages.gogol-customsearch
    pkgs.rPackages.jetpack
    pkgs.rPackages.annotatr
    pkgs.rPackages.dotwhisker
    pkgs.sutils
    pkgs.rPackages.bfw
    pkgs.rPackages.adnuts
    pkgs.perl532Packages.TextWrapI18N
    pkgs.python38Packages.dnslib
    pkgs.ocamlPackages.dns-cli
    pkgs.dnsenum
    pkgs.dnsviz
    pkgs.ocamlPackages.dns-tsig
    pkgs.dnscontrol
    pkgs.haskellPackages.nonemptymap
    pkgs.haskellPackages.gogol-android-publisher
    pkgs.haskellPackages.network-data
    pkgs.prometheus-dnsmasq-exporter
    pkgs.ocamlPackages.dns-stub
    pkgs.ocamlPackages.dns
    pkgs.ocamlPackages.dns-client
    pkgs.ocamlPackages.dns-server
    pkgs.haskellPackages.dnscache
    pkgs.dnsdist
    pkgs.ocamlPackages.dns-resolver
    pkgs.python38Packages.dnspython
    pkgs.python38Packages.dns
    pkgs.haskellPackages.dns
    pkgs.haskellPackages.dnssd
    pkgs.dnscrypt-proxy2
    pkgs.python39Packages.dns
    pkgs.libint
    pkgs.python39Packages.pysma
    pkgs.rPackages.LDRTools
    pkgs.rPackages.d3Network
    pkgs.rPackages.wordpressr
    pkgs.wordpress
    pkgs.haskellPackages.wordpress-auth
    pkgs.hostapd
    pkgs.unixtools.hostname
    pkgs.hostname
    pkgs.haskellPackages.gogol-plus-domains
    pkgs.perlPackages.DataValidateDomain
    pkgs.haskellPackages.domain-auth
  ];
}
