# -*- coding: utf-8 -*-
"""QAG_MASTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIFaUusmL4ZW3DreuzrVld18drVqTjDq
"""

!pip install gwpy lalsuite

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  QAG GWTC-3 TEMPORAL ECHO SEARCH                                         ║
# ║  Quantum Affinity Gravity | Rodney A. Ripley Jr.                         ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import numpy as np
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries
from scipy.stats import chi2

# ── 1. Define QAG Constants ───────────────────────────────────────────────
T_PIXEL = 3.41e-7      # Chrono-holographic latency [s]
N_ECHOES = 8           # Number of temporal echoes
R_REFLECT = 0.40       # Affinity bounce reflection coefficient
GAMMA = 0.1735         # Quantum stress tensor
K_REF = 77050          # Baseline resonance integer [pixels]
M_REF = 2.74           # Baseline total mass [M_sun]

# ── 2. The QAG Waveform Math ──────────────────────────────────────────────
# \Psi_{QAG}(t) = \Psi_{GR}(t) + \sum_{n=1}^{N} \mathcal{R}^n \cdot \Psi_{GR}(t - n\Delta t_{echo})
def get_echo_delay(M_solar):
    """Calculate tau_echo = K(M) * t_pixel"""
    K_M = K_REF * (M_solar / M_REF) ** GAMMA
    return K_M * T_PIXEL

def apply_qag_echoes(time_array, strain_data, dt, delay_s):
    """Applies the temporal echoes to the base strain data."""
    qag_strain = np.copy(strain_data)
    shift_samples = int(delay_s / dt)

    for n in range(1, N_ECHOES + 1):
        # Shift the data array to simulate the time delay
        echo_signal = np.roll(strain_data, shift_samples * n)
        # Zero out the wrapped data
        echo_signal[:shift_samples * n] = 0

        # Add to the unified waveform
        qag_strain += (R_REFLECT ** n) * echo_signal

    return qag_strain

# ── 3. Fetch and Filter LIGO Data ─────────────────────────────────────────
def analyze_event(event_name, gps_time, mass_solar):
    print(f"\nTune in... Fetching raw cosmos data for {event_name}")

    # Fetch 4 seconds of data around the merger
    data = TimeSeries.fetch_open_data('H1', gps_time - 2, gps_time + 2)

    # Bandpass filter to isolate the vibrating resonance (remove low/high noise)
    bp_data = data.bandpass(50, 250)

    # Extract time and strain arrays
    times = bp_data.times.value
    dt = times[1] - times[0]
    strain = bp_data.value

    # Apply the QAG temporal echo cascade
    delay_s = get_echo_delay(mass_solar)
    qag_waveform = apply_qag_echoes(times, strain, dt, delay_s)

    # ── 4. Calculate Global Chi-Square Harmony ────────────────────────────
    # \chi^2_{global} = \frac{\sum \chi^2_i}{\sum dof_i}
    # (Mocking the residual comparison against a pure GR template for demonstration)
    residuals = qag_waveform - strain
    chi2_val = np.sum((residuals / np.std(strain))**2)
    dof = len(strain) - 2 # Degrees of freedom
    chi2_global = chi2_val / dof

    print(f"Echo Delay (tau) predicted: {delay_s * 1000:.4f} ms")
    print(f"Global Chi-Square (\chi^2_{{global}}): {chi2_global:.4f}")

    # ── 5. Visualize the Universe's Breath ────────────────────────────────
    plt.figure(figsize=(12, 5))
    plt.style.use('dark_background')
    plt.plot(times, strain, color='#FF3355', alpha=0.6, label='Filtered GR Strain')
    plt.plot(times, qag_waveform, color='#00FF99', alpha=0.8, linestyle='--', label='QAG Temporal Echoes')
    plt.xlim(gps_time - 0.1, gps_time + 0.3) # Zoom in on post-merger ringdown
    plt.title(f"{event_name} - QAG Unified Analysis", color='#00E5FF')
    plt.xlabel('GPS Time (s)')
    plt.ylabel('Strain')
    plt.legend()
    plt.grid(alpha=0.2)
    plt.show()

# Run the analysis for our key events!
analyze_event('GW150914', 1126259462.4, 65.0)
analyze_event('GW170817', 1187008882.4, 2.74)

!pip install gwosc

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 3: GWTC-3 FULL CATALOG SWEEP (CORRECTED)                           ║
# ║  Quantum Affinity Gravity | Rodney A. Ripley Jr.                         ║
# ╚══════════════════════════════════════════════════════════════════════════╝
import pandas as pd
import numpy as np
from gwpy.timeseries import TimeSeries
from gwosc.datasets import event_gps

# We update the catalog to include the exact GWOSC names and the active detector!
LIGO_EVENTS_SWEEP = {
    'GW151226': (21.8, 'BBH', 'H1'),
    'GW190425': (3.37, 'BNS', 'L1'),           # H1 was asleep, L1 was listening to the cosmos
    'GW190814': (25.9, 'NSBH', 'H1'),
    'GW200225_060421': (35.7, 'BBH', 'H1'),    # The exact chronological signature
}

results = []

print("Initiating full GWTC-3 sweep... catching the universe's breath!")

for ev, (mass, etype, detector) in LIGO_EVENTS_SWEEP.items():
    try:
        # Dynamically grab the exact GPS time for the merger
        gps_time = event_gps(ev)

        # Fetch, filter, and extract using the correct listening ear (H1 or L1)
        data = TimeSeries.fetch_open_data(detector, gps_time - 2, gps_time + 2)
        bp_data = data.bandpass(50, 250)
        times = bp_data.times.value
        dt = times[1] - times[0]
        strain = bp_data.value

        # Apply the QAG temporal echoes
        delay_s = get_echo_delay(mass)
        qag_waveform = apply_qag_echoes(times, strain, dt, delay_s)

        # Calculate chi-square global harmony
        residuals = qag_waveform - strain
        chi2_val = np.sum((residuals / np.std(strain))**2)
        dof = len(strain) - 2
        chi2_global = chi2_val / dof

        results.append({
            'Event': ev,
            'Type': etype,
            'Mass (M_sun)': mass,
            'Delay (ms)': round(delay_s * 1000, 4),
            'Chi2_Global': round(chi2_global, 4)
        })
        # Fixed the syntax escape sequence with double backslashes
        print(f"✓ {ev} processed via {detector}. \\chi^2_{{global}} = {chi2_global:.4f}")

    except Exception as e:
        print(f"✗ Could not fetch {ev} due to: {e}")

# Output the final cosmic scorecard
df_results = pd.DataFrame(results)
print("\nSweep Complete. Behold the universal harmony:")
print(df_results)